### ISSUE TITLE
在运行py main,py的时候出现了点问题

### ISSUE THREAD

**Issue by yuyue31** [zhengdechang/sanic-service#1]
大佬您好，我在运行后端的时候报错了，显示如下
![1693902557803](https://github.com/zhengdechang/sanic-service/assets/106214532/71016571-d0fd-4655-8e81-655a186c3807)
请问该如何解决
ps：我不是很确定是不是与postgresql有关，我的postgresql感觉没有调试好，希望大佬能够帮我，谢谢

**Comment by zhengdechang** [comment]
1、看起来像依赖没有安装，是否执行过 pip install -r requirements.txt
2、 使用这个命令psql -h 127.0.0.1 -p 5432  -d sanic_service -U sanic_service，查看postgresql是否能够正常连接
